In [1]:
#pip install transformers

#pipelines can simplify the pretrained models;

#transeformers library

from transformers import pipeline

None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.


In [7]:
#pipeline means flow of data from original system to destination system;

import transformers

print(transformers.__version__)

4.52.1


In [8]:
import librosa

#librosa is a python package for music and audio 

In [9]:
import torch

In [10]:
import IPython.display as display

In [11]:
from transformers import Wav2Vec2ForCTC,Wav2Vec2ForCTC,Wav2Vec2Tokenizer

In [12]:
import numpy as np

In [51]:
tokenizer=Wav2Vec2Tokenizer.from_pretrained("facebook/wav2vec2-base-960h")

model=Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-base-960h")


                                        

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'Wav2Vec2CTCTokenizer'. 
The class this function is called from is 'Wav2Vec2Tokenizer'.
C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\wav2vec2\tokenization_wav2vec2.py:720: FutureWarning: The class `Wav2Vec2Tokenizer` is deprecated and will be removed in version 5 of Transformers. Please use `Wav2Vec2Processor` or `Wav2Vec2CTCTokenizer` instead.
  warnings.warn(
Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [73]:
audio,sampling_rate=librosa.load("welcome.mp3",sr=16000)




In [74]:
audio,sampling_rate

(array([ 3.8172916e-15,  4.6376731e-15, -1.8577743e-15, ...,
        -1.2309004e-08, -1.3518152e-08,  8.5903791e-09],
       shape=(24242,), dtype=float32),
 16000)

In [75]:
display.Audio('welcome.mp3',autoplay=True)

In [76]:
import sys

sys.path.append("download")   
    #sys.path.append("/path/to/your/audio/directory")
import pygame
pygame.mixer.init()
sound = pygame.mixer.Sound("welcome.mp3")
sound.play()




In [77]:
input_values=tokenizer(audio,return_tensors='pt').input_values

input_values

tensor([[0.0017, 0.0017, 0.0017,  ..., 0.0017, 0.0017, 0.0017]])

In [78]:
logits=model(input_values).logits

logits

tensor([[[ 14.9526, -28.9092, -28.6293,  ...,  -7.8288,  -7.7545,  -6.3183],
         [ 14.9650, -28.9960, -28.7129,  ...,  -7.8644,  -7.6698,  -6.4226],
         [ 14.1891, -27.2919, -27.0289,  ...,  -6.2607,  -7.5236,  -5.2059],
         ...,
         [ 14.5053, -28.0223, -27.7766,  ...,  -7.6143,  -7.6994,  -6.1223],
         [ 14.1930, -27.2807, -27.0171,  ...,  -6.2437,  -7.5237,  -5.1823],
         [ 14.5615, -28.2274, -27.9752,  ...,  -7.7583,  -7.8707,  -6.3241]]],
       grad_fn=<ViewBackward0>)

In [79]:
predicted_ids=torch.argmax(logits,dim=-1)

In [80]:
transciptions=tokenizer.decode(predicted_ids[0])

In [81]:
transciptions

'WELCOME TO MY STREAM'

In [83]:
print("OK Done")

OK Done
