In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [2]:
df=pd.read_csv("Iris.csv")
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [3]:
df=df.drop("Id",axis=1)

In [4]:
df.dtypes

SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [6]:
from sklearn.decomposition import PCA

In [8]:
df_num=df.select_dtypes(include="float64")

In [10]:
df_num.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [13]:
ms=MinMaxScaler()
df_num_sc=ms.fit_transform(df_num)

In [15]:
df_num_df=pd.DataFrame(df_num_sc,index=df_num.index,columns=df_num.columns)

In [16]:
df_final=pd.concat([df_num_df,df["Species"]],axis=1)

In [17]:
df_final.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0       0.222222      0.625000       0.067797      0.041667  Iris-setosa
1       0.166667      0.416667       0.067797      0.041667  Iris-setosa
2       0.111111      0.500000       0.050847      0.041667  Iris-setosa
3       0.083333      0.458333       0.084746      0.041667  Iris-setosa
4       0.194444      0.666667       0.067797      0.041667  Iris-setosa

In [18]:
pca=PCA(n_components=2)

In [19]:
x=df.drop("Species",axis=1)
y=df["Species"]

In [20]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=100)

In [21]:
pca.fit(x_train)

PCA(n_components=2)

In [22]:
x_train_pca=pca.transform(x_train)

In [23]:
x_train_pca

array([[-1.47217049e-01, -6.39326920e-01],
       [ 3.45987694e-01, -3.11740339e-01],
       [ 1.34252822e+00, -7.24315620e-01],
       [-2.74110414e+00, -1.87111410e-01],
       [-2.57231676e+00,  8.54884390e-01],
       [ 9.80952332e-01,  3.53578726e-01],
       [-2.48599434e+00,  5.48791284e-01],
       [ 2.11250267e-01, -6.44104942e-01],
       [ 2.20002826e+00,  1.65704784e-01],
       [ 1.63727858e+00, -5.12455101e-01],
       [-2.80955346e+00, -8.92827259e-01],
       [ 5.11369308e-01, -6.32995072e-01],
       [ 2.66379307e+00,  3.74520971e-01],
       [ 2.97082593e+00,  8.08245908e-01],
       [-2.62706786e+00, -6.60188386e-02],
       [-2.76983425e+00, -4.47644344e-02],
       [-2.46210525e+00, -9.86628992e-02],
       [-2.49234020e+00,  4.76891529e-01],
       [ 2.74449329e-01, -3.65431393e-01],
       [-2.62706786e+00, -6.60188386e-02],
       [-2.25474362e+00,  1.42795978e-01],
       [-2.82058234e+00,  1.16660888e-01],
       [ 1.13214714e+00,  1.11186172e-01],
       [ 3.

In [25]:
pca.explained_variance_ratio_

array([0.91850827, 0.05855916])

In [28]:
pca

PCA(n_components=2)

In [30]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis


In [33]:
lda=LinearDiscriminantAnalysis()
x_train_lda=lda.fit_transform(x_train,y_train)

In [35]:
lda.explained_variance_ratio_

array([0.99170061, 0.00829939])